README.md
sync/evmdownloader.go
sync/evmdownloader_test.go

**This is a cherry-pick from CDK** [PR#289](https://github.com/0xPolygon/cdk/pull/289)
When any synchronize exceeds the block finalized keep asking continously for same range without any sleep, and don't extend the range to reach the lastest block
- The idea is to extend the range to go to the lastest block seen on network, 
Here the explanation of[ how must work ](https://github.com/0xPolygon/cdk/pull/272#discussion_r1925281478) the range when we are > finalized: 
```
2025-01-29T11:11:21.890+0100	INFO	sync/evmdownloader.go:138	getting events from blocks 665 to  681. lastFinalizedBlock: 670	{"pid": 156441, "version": "v0.1.0", "syncer": "l1infotreesync"}
2025-01-29T11:11:21.893+0100	INFO	sync/evmdownloader.go:138	getting events from blocks 665 to  681. lastFinalizedBlock: 670	{"pid": …
```

fix: syncer spamming RPC and reaching tip of chain (cherry-pick from CDK)

---

agglayer/types.go
agglayer/types_test.go
aggsender/aggsender.go
aggsender/aggsender_test.go
aggsender/block_notifier_polling.go
aggsender/block_notifier_polling_test.go
aggsender/config.go
aggsender/epoch_notifier_per_block.go
aggsender/epoch_notifier_per_block_test.go
aggsender/mocks/mock_block_notifier.go
aggsender/mocks/mock_epoch_notifier.go
aggsender/types/block_notifier.go
aggsender/types/epoch_notifier.go
common/rate_limit.go
common/rate_limit_test.go
config/config_test.go
config/default.go
sync/mock_evm_downloader_full.go
test/bats/helpers/lxly-bridge.bash
test/config/kurtosis-cdk-node-config.toml.template

Fixes #47
- The `aggsender`is going to check periodically the status of certificates (`AggSender.CheckStatusCertificateInterval`) and rebuild certificate as soon as `InError`is detected.
- To avoid spamming Agglayer implements a rate limiter
- To avoid submit a certificate too close to end of a epoch avoid to send certificates after reaching a percentage of epoch.
```
[AggSender]
CheckStatusCertificateInterval = "5m"
```
- Rate limit configuration:
```
[AggSender.MaxSubmitCertificateRate]
NumRequests = 20
Interval = "1h"
```
It can be disabled setting `NumRequests` to 0
- Configuration of percentatge that we can't submit a new certificate to agglayer:
```
[AggSender]
MaxEpochPercentageAllowedToSendCertificate=80
```
A value of 0 or > 100 disable this check

feat: resend failed certificate

---

aggsender/block_notifier_polling_test.go
bridgesync/bridgesync.go
bridgesync/bridgesync_test.go
bridgesync/e2e_test.go
bridgesync/mocks/mock_reorg_detector.go
cmd/run.go
config/config_test.go
config/default.go
etherman/types.go
etherman/types_test.go
l1infotreesync/mocks/mock_reorg_detector.go
reorgdetector/config.go
reorgdetector/reorgdetector.go
reorgdetector/reorgdetector_test.go
sync/evmdownloader.go
sync/evmdriver.go
sync/mock_reorg_detector.go
test/helpers/e2e.go

Fixes #176
- Reorg detector allow to configure the what kind of block is a finalized block (`ReorgDetectorLX.FinalizedBlock`)
- Syncers use finalizedBlock configuration from reorgDetector
- Fix e2e test for bridgesyncer that sometimes fails because a forced reorg affect to a finalized block
```
[ReorgDetectorL1]
DBPath = "{{PathRWData}}/reorgdetectorl1.sqlite"
FinalizedBlock="FinalizedBlock"
[ReorgDetectorL2]
DBPath = "{{PathRWData}}/reorgdetectorl2.sqlite"
FinalizedBlock="LatestBlock"
```

feat: allows reorg detectors configure the what kind of block is a finalized block

---

bridgesync/bridgesync.go
bridgesync/bridgesync_test.go
config/config.go
config/config_test.go

- A common mistake is to set the variable `polygonBridgeAddr` inside the section `[L1Config]` in config file. This is prevented with the list of deprecated variables on config file
- Another possible error is to set the wrong address. To fix that the code checks that the contract is the bridge one testing a method.
Fixes #167

feat: Prevent missconfiguration of bridgeAddress in bridgesyncer

---

aggsender/aggsender.go
aggsender/aggsender_test.go
aggsender/config.go
aggsender/flow_aggchain_prover.go
aggsender/flow_aggchain_prover_test.go
aggsender/types/types.go
config/default.go
docs/aggsender.md
test/config/kurtosis-cdk-node-config.toml.template

This PR introduces couple of improvements to the `aggsender`:
1. Remove unnecessary `SaveCertificatesToFilesPath` config parameter, which was used to save certificates we send to the `agglayer` to some temporary file. Since we are already saving the entire `json` format to the `aggsender` `db`, this became redundant.
2. Expanded the `aggsender.md` with new configuration parameters that were added in couple of previous PRs.
3. Removed the check for pending certificates in the `sendCertificate` function, since we are already checking this before we make a call to that function.
4. In the `aggchain prover flow`, when we are resending the certificate that is `InError`, we will always make a call to the `aggchain prover` to get the proof, even though we might have it, because, the previously …

feat: small improvements on the `aggsender`

---

.github/workflows/lint.yml
.golangci.yml

Fix the `golangci-lint` configuration (remove the obsolete fields) and bump the version of the `golangci-lint` version to v1.64.5 and `golangci-lint-action` to v6.5.0.

fix: the `golangci-lint` configuration and bump `golangci-lint` version

---

bridgesync/bridgesync.go
bridgesync/bridgesync_test.go
bridgesync/downloader.go
bridgesync/migrations/bridgesync0002.sql
bridgesync/migrations/migrations_test.go
bridgesync/processor.go
bridgesync/processor_test.go
rpc/bridge.go
rpc/bridge_interfaces.go
rpc/bridge_test.go
rpc/mocks/mock_bridger.go
rpc/openrpc.json
test/bats/helpers/lxly-bridge.bash
test/bats/pp/bridge-e2e.bats

This PR exposes a JSON-RPC endpoint to fetch bridge claims. It returns all claimed transactions on the network, sorted in descending order by globalIndex, with support for pagination.

feat: `bridge_getClaims` endpoint

---

test/combinations/fork12-pessimistic-multi-attach-second-cdk.yml
test/combinations/fork12-pessimistic-multi.yml
test/combinations/fork12-pessimistic.yml

This PR adapts the Kurtosis configuration in the repository, as there are new changes in the https://github.com/0xPolygon/kurtosis-cdk/tree/feat/enable-bridge-service-for-aggkit, which is used as a reference when running the e2e tests in the aggkit.

fix: upgrade kurtosis config

---

bridgesync/processor.go
bridgesync/processor_test.go
rpc/bridge.go
rpc/bridge_test.go

This PR encodes the metadata fields in the bridge and token mappings in a hex format.

feat: encode bridge and token mapping metadata hex

---

sync/evmdownloader.go
sync/evmdownloader_test.go

This is a cherry-pick of this [PR](https://github.com/0xPolygon/cdk/pull/302) from CDK

fix: fix downloader latest block

---

test/bats/helpers/lxly-bridge.bash
test/bats/pp-multi/bridge-l2_to_l2-e2e.bats
test/bats/pp/bridge-e2e-msg.bats
test/bats/pp/bridge-e2e.bats

Added bats e2e for`bridge_getClaims` endpoint

test: e2e`bridge_getClaims`

---

bridgesync/processor.go
bridgesync/processor_test.go
docs/bridge_service.md

Update `bridge_getClaims` endpoint to return result in descending order of `block_num` and `block_pos`

feat: update claims api

---

bridgesync/bridgecalldata_test.go
bridgesync/claimcalldata_test.go
bridgesync/helpers_test.go

Stabilize the flaky claim calldata test, by waiting for the transaction receipt in a loop (e.g. https://github.com/agglayer/aggkit/actions/runs/13843134128/job/38735246814).

fix: wait for transaction receipt in a loop in claim calldata test

---

agglayer/types.go
aggsender/flow_aggchain_prover.go
aggsender/flow_aggchain_prover_test.go
aggsender/grpc/aggchain_proof_client.go
aggsender/grpc/aggchain_proof_client_test.go
aggsender/mocks/mock_aggchain_proof_client_interface.go
go.mod
go.sum

This PR adds `BlockNumber` fields to `inserted GERs` and `Imported Bridge Exits` that are sent to the `aggkit prover` to generate proof.
Fixes #304

feat: add block num

---

reorgdetector/reorgdetector_db.go
reorgdetector/reorgdetector_test.go

The current implementation of `getTrackedBlocks` fails to correctly handle the scenario where the `SubscriberID` changes on the last element of `headersWithID`. Rather than creating a new `HeadersList` for the new `SubscriberID`, it mistakenly adds it to the existing `HeadersList` of a different `SubscriberID`.

fix: Reorgdetector 

---

aggoracle/chaingerreader/evm.go
aggoracle/chaingerreader/evm_test.go
aggsender/flow_aggchain_prover.go
aggsender/flow_aggchain_prover_test.go
aggsender/mocks/mock_chain_ger_reader.go
aggsender/types/types.go

This PR fixes the sending of `ProvenInsertedGERWithBlockNumber` when asking for `aggchain proof` from the `aggkit prover`.
These `ProvenInsertedGERWithBlockNumber` are injected GERs on L2 for which the `aggsender` generates proofs on a finalized l1 info tree root, but they need the L2 block to be sent in which they were included so that the prover, if the need arises, can cut the range accordingly.

fix: injected GER with block number

---

.mockery.yaml
aggoracle/chaingerreader/evm.go
aggoracle/chaingerreader/evm_test.go
aggoracle/chaingersender/evm.go
aggoracle/mocks/mock_l2_ger_manager_contract.go
aggoracle/types/types.go
bridgesync/bridgesync.go
bridgesync/downloader.go
claimsponsor/evmclaimsponsor.go
etherman/contracts/base_test.go
etherman/contracts/contracts_banana.go
etherman/contracts/contracts_elderberry.go
etherman/etherman.go
etherman/types.go
go.mod
go.sum
l1infotreesync/downloader.go
l1infotreesync/downloader_test.go
l1infotreesync/e2e_test.go
lastgersync/evmdownloader.go
test/helpers/e2e.go
test/helpers/mock_ethtxmanager.go
test/helpers/simulated.go

This PR updates the reference to `cdk-contracts-tooling` repo, and changes the way we read the injected GERs in the `aggoracle/chaingerreader` package, since the event for inserting a `GER` in `L2` changed on the new contracts version.
Rest of the changes are just update of the packages that reference packages of `cdk-contracts-tooling` repo.

feat: update `cdk-contracts-tooling` reference

---

.github/workflows/build-aggkit-image.yml
.github/workflows/codeql.yml
.github/workflows/lint.yml
.github/workflows/test-e2e-multi-chains.yml
.github/workflows/test-e2e-single-chain.yml
.github/workflows/test-unit.yml
Dockerfile
go.mod

This PR bumps the go version to `v1.24`.
Fixes #352

chore: update Go version to 1.24

---

go.mod

This PR pins specific version 1.24.2 in the `go.mod` file.

feat: pin 1.24.2 go version in go.mod

---

agglayer/grpc/agglayer_grpc_client.go
agglayer/grpc/agglayer_grpc_client_test.go
agglayer/types/types.go
agglayer/types/types_test.go
aggsender/flows/flow_aggchain_prover.go
go.mod
go.sum
test/combinations/fork12-pessimistic-multi.yml
test/combinations/fork12-pessimistic.yml

This PR updates `agglayer` API for sending certificates. Now the `agglayer` receives `Vkey` and `Version` alongside the `SP1StarkProof` in the certificate.
This data is returned by the `aggkit-prover` to `aggsender` and `aggsender` packs it to a certificate and sends it to `agglayer`.

feat: update `agglayer` API on `aggsender`

---

agglayer/grpc/agglayer_grpc_client.go
aggsender/aggsender.go
aggsender/grpc/aggchain_proof_client.go
common/grpc_client.go
common/grpc_client_test.go
test/config/aggkit-node-config.toml.template

Errors returned by `aggkit prover` and `agglayer` are in the `google ErrorInfo` format:
- spec: https://google.aip.dev/193#error_model
- definition: https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto
so we can easily unpack them to now details of the messages and why the calls failed.
This PR also moves initialization of the signer private key in `aggsender` only if the `aggsender.Mode` is `PessimisticProof`, since the `AggchainProof` mode does not require a signer. This also enables users to not define the signer in the case of `AggchainProof` mode, since it is not needed.

feat: unpack `grpc` errors

---

aggoracle/chaingersender/evm.go
bridgesync/bridgecalldata_test.go
bridgesync/bridgesync.go
bridgesync/bridgesync_test.go
bridgesync/downloader.go
bridgesync/downloader_test.go
bridgesync/migrations/bridgesync0003.sql
bridgesync/migrations/migrations.go
bridgesync/migrations/migrations_test.go
bridgesync/processor.go
bridgesync/processor_test.go
claimsponsor/evmclaimsponsor.go
etherman/contracts/base_test.go
etherman/contracts/contracts_banana.go
etherman/contracts/contracts_elderberry.go
etherman/etherman.go
etherman/types.go
go.mod
go.sum
l1infotreesync/downloader.go
l1infotreesync/downloader_test.go
l1infotreesync/e2e_test.go
lastgersync/evmdownloader.go
rpc/bridge.go
rpc/bridge_interfaces.go
rpc/bridge_test.go
rpc/mocks/mock_bridger.go
test/bats/pp/bridge-e2e.bats
test/helpers/e2e.go
test/helpers/simulated.go

Index the following sovereign chain bridge contract events:
- `SetSovereignTokenAddress` - expose it via the `bridge_getTokenMappings` JSON RPC endpoint
- `MigrateLegacyToken` - exposed via `bridge_getLegacyTokenMigrations` JSON RPC endpoint
- `RemoveLegacySovereignTokenAddress` - indexed and it reflects the legacy token migrations.
Fixes #298

feat: index sovereign chain L2 bridge contracts events

---

aggsender/aggsender.go
aggsender/aggsender_test.go
aggsender/config.go
aggsender/flows/flow_aggchain_prover.go
aggsender/flows/flow_aggchain_prover_test.go
aggsender/flows/flow_base.go
aggsender/flows/flow_pp_test.go
aggsender/prover/proof_generation_tool.go
aggsender/prover/proof_generation_tool_test.go
config/default.go

This PR adds the logic to read the start block on L2 from the `soverign rollup` contract from which proofs will be generated and certificates created.
For this purpose, we added a `SovereignRollupAddr` field to the `aggsender` config, which is needed for the `AggchainProof` mode of the `aggsender`.

feat: `op` start block config

---

agglayer/types/types.go
aggoracle/chaingerreader/evm.go
aggoracle/chaingerreader/evm_test.go
aggoracle/mocks/mock_l2_ger_manager_contract.go
aggoracle/types/types.go
aggsender/flows/flow_aggchain_prover.go
aggsender/flows/flow_aggchain_prover_test.go
aggsender/grpc/aggchain_proof_client.go
aggsender/mocks/mock_chain_ger_reader.go
aggsender/types/types.go
go.mod
go.sum

This PR adds the `block index` field to the `ProvenInsertedGERWithBlockNumber` and sends it to the `aggkit prover` so that the prover can properly sort the injected GERs when building a proof.

feat: add block index to injected GERs we send to the prover

---

aggsender/aggsender.go
aggsender/aggsender_test.go
aggsender/flows/flow_aggchain_prover.go
aggsender/flows/flow_aggchain_prover_test.go
aggsender/flows/flow_base.go
aggsender/flows/flow_base_test.go
aggsender/flows/flow_pp.go
aggsender/flows/flow_pp_test.go

This PR allows sending of empty certificates (certificates without bridge exits and claims) to the `agglayer` in case of `AggchainProof` mode on `aggsender`. This is needed so that `FEP` can work properly on the network.

feat: allow empty certificates for `FEP` (aggchain proof) flow

---

aggsender/aggsender.go
aggsender/flows/flow_aggchain_prover.go
aggsender/flows/flow_aggchain_prover_test.go
aggsender/flows/flow_base.go
aggsender/flows/flow_pp.go
aggsender/flows/flow_pp_test.go
aggsender/types/certificate_build_params.go

This PR fixes the way `InError` certificate is resent to the `agglayer` in the new `FEP` (`AggchainProof`) mode on `aggsender`.
Since proof was already generated by the prover, we just need to resend it back to the `agglayer`. No need to call the prover again.

fix: resend proof in `AggchainProof` flow

---

bridgesync/claimcalldata_test.go
bridgesync/downloader.go
bridgesync/e2e_test.go
bridgesync/processor.go
bridgesync/processor_test.go
cmd/run.go

Populate `from_address` based on the tx sender for bridge and claim transactions.
Fixes #368

feat: populate from_address based on tx sender

---

bridgesync/bridgesync_test.go
bridgesync/processor.go
bridgesync/processor_test.go
rpc/bridge.go
rpc/bridge_interfaces.go
rpc/bridge_test.go
rpc/openrpc.json

- Propagate consistent error codes in all endpoints exposed by the bridge service.
- Return empty result set, instead of error in case the result is not found.
- Update the Open RPC definition with the missing `bridge_getLegacyTokenMigrations` function.
Fixes #392

feat: bridge service return consistent error codes

---

aggsender/types/certificate_build_params.go
common/common.go
common/common_test.go

This PR optimizes the `Range()` on `CertificateBuildParams` struct which cuts the claims and bridges from the certificate based on the new range gotten from the prover.
The function now estimates the capacity of new slices to minimize the memory and CPU overhead.

fix: optimize `Range` function on `CertificateBuildParams`

---

cmd/run.go
config/config.go
config/config_test.go
config/default.go
pprof/config.go
pprof/pprof.go
pprof/pprof_test.go

This PR enables `pprof` profiling on `aggkit` app so that we can run different profiles for easier finding of leaks, weak points, and non-optimized parts of the application.
A new config is added to the `aggkit`:
```
[Profiling]
ProfilingHost = "localhost"
ProfilingPort = 6060
ProfilingEnabled = true
```
If `ProfilingEnabled` is true, the `pprof` server will start on designated port in the `aggkit` app.
**IMPORTANT NOTE**: The code is taken from `cdk-validium-node`.

feat: enable `pprof`

---

aggsender/flows/flow_aggchain_prover.go
aggsender/flows/flow_aggchain_prover_test.go
aggsender/flows/flow_base.go
aggsender/flows/flow_pp_test.go

This PR fixes the case where in `PP` to `FEP` upgrade we have a gap between the last settled block in `PP` and the start block for `FEP` that is defined in the `FEP` rollup contract (this start block defines a block from which spans are created).

fix: `PP` to `FEP` upgrade `startBlock`

---

docs/aggoracle.md

Hi! I fixed a broken link to CDK contracts tooling in the AggOracle documentation. The repository structure changed, making the previous path invalid.

chore: Fixed dead link in `aggoracle.md`
